
package jamp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketService", targetNamespace = "http://service.jamp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketService {


    /**
     * 
     * @param arg0
     * @return
     *     returns jamp.service.ReserveResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveTicket", targetNamespace = "http://service.jamp/", className = "jamp.service.ReserveTicket")
    @ResponseWrapper(localName = "reserveTicketResponse", targetNamespace = "http://service.jamp/", className = "jamp.service.ReserveTicketResponse")
    public ReserveResponse reserveTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        ReserveRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns jamp.service.TicketinfoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketInfo", targetNamespace = "http://service.jamp/", className = "jamp.service.GetTicketInfo")
    @ResponseWrapper(localName = "getTicketInfoResponse", targetNamespace = "http://service.jamp/", className = "jamp.service.GetTicketInfoResponse")
    public TicketinfoResponse getTicketInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        TicketInfoRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns jamp.service.TicketResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payForTicket", targetNamespace = "http://service.jamp/", className = "jamp.service.PayForTicket")
    @ResponseWrapper(localName = "payForTicketResponse", targetNamespace = "http://service.jamp/", className = "jamp.service.PayForTicketResponse")
    public TicketResponse payForTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns jamp.service.TicketResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTicket", targetNamespace = "http://service.jamp/", className = "jamp.service.ReturnTicket")
    @ResponseWrapper(localName = "returnTicketResponse", targetNamespace = "http://service.jamp/", className = "jamp.service.ReturnTicketResponse")
    public TicketResponse returnTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
